/**
 * @Copyright: Copyright (c) 2010 TelenavSoftware, Inc. All rights reserved.
 */
package com.dev.cty.validation;

public enum ErrorType {

	PRECONDITION_FAILED_CONSTRAINT_ASSERT_FALSE(1000),

	PRECONDITION_FAILED_CONSTRAINT_ASSERT_TRUE(1001),

	PRECONDITION_FAILED_CONSTRAINT_DECIMAL_MAX(1002),

	PRECONDITION_FAILED_CONSTRAINT_DECIMAL_MIN(1003),

	PRECONDITION_FAILED_CONSTRAINT_DIGITS(1004),

	PRECONDITION_FAILED_CONSTRAINT_FUTURE(1005),

	PRECONDITION_FAILED_CONSTRAINT_MAX(1006),

	PRECONDITION_FAILED_CONSTRAINT_MIN(1007),

	PRECONDITION_FAILED_CONSTRAINT_NOT_NULL(1008),

	PRECONDITION_FAILED_CONSTRAINT_NULL(1009),

	PRECONDITION_FAILED_CONSTRAINT_PAST(1010),

	PRECONDITION_FAILED_CONSTRAINT_PATTERN(1011),

	PRECONDITION_FAILED_CONSTRAINT_SIZE(1012),

	PRECONDITION_FAILED_CONSTRAINT_CREDIT_CARD_NUMBER(1013),

	PRECONDITION_FAILED_CONSTRAINT_EMAIL(1014),

	PRECONDITION_FAILED_CONSTRAINT_LENGTH(1015),

	PRECONDITION_FAILED_CONSTRAINT_NOT_BLANK(1016),

	PRECONDITION_FAILED_CONSTRAINT_NOT_EMPTY(1017),

	PRECONDITION_FAILED_CONSTRAINT_SCRIPT_ASSERT(1018),

	PRECONDITION_FAILED_CONSTRAINT_URL(1019),

	PRECONDITION_FAILED_NO_DETAIL_REASION(1099),

	HAS_APPLIED_THIS_EVENT(2000),

	HAS_NOT_APPLIED_THIS_EVENT(2001),

	HAS_NOT_CHECKIN_THIS_EVENT(2002),

	ACCOUNT_EXIST(2003),

	ACCOUNT_NICKNAME_EXIST(2004),

	ACCOUNT_OLDPASSWORD_INVALID(2005),

	SESSION_AUTHENTICATION_FAILURE(2006),

	SESSION_LOGINTYPE_ERROR(2007),

	SESSION_SINAACCOUNT_INVALID(2008),

	SESSION_ACCOUNTORPASSWORD_ERROR(2009),

	HAVE_EXCEED_ENCOUNTER_PERMISSION(2010),

	CANNOT_FIND_MATCHED_ENCOUNTER(2011),

	CANNOT_MAKE_FRIEND_MYSELF(2012),

	RELATIONSHIP_HAVE_INVITED(2013),

	RELATIONSHIP_HAVE_REMOVED(2014),

	RELATIONSHIP_HAVE_BEEN_FRIEND(2015),

	RELATIONSHIP_HAVE_BEEN_NOT_FRIEND(2016),

	CANNOT_FAVOTITE(2017),

	HAS_FAVORITED(2018),

	EMOTION_DESCRIPTION_CANNOT_BE_NULL(2019),

	PHOTO_DATA_CANNOT_BE_NULL(2020),

	QR_NOT_FOUND(2021),

	QR_FORMAT_ERROR(2022),

	QR_EVENT_NOT_MATCH(2023),

	ACCOUNT_LOCKED(2024),

	EMAIL_AUTHENTICATION_HAS_FINISHED(2025),

	PHONE_AUTHENTICATION_HAS_FINISHED(2026),

	AUTHENTICATION_EMAIL_HAS_USED(2027),

	AUTHENTICATION_PHONE_HAS_USED(2028),

	EVENT_APPLICANT_OVER_LIMIT(2030),

	CANNOT_SHARE(2031),

	SESSION_TENCENTACCOUNT_INVALID(2032),

	CANNOT_BIND_ANOTHER_TENCENT_ACCOUNT(2033),

	DOODLE_DESCRIPTION_CANNOT_BE_NULL(2034),

	ACQUIRE_MSN_CONTACT_FAILED(2035),

	NEED_UNBLOCK(2036),

	NEED_BIND_THIRD_PARTY_ACCOUNT(2037),

	CANNOT_BIND_RENREN_ACCOUNT(2038),

	SESSION_RENRENACCOUNT_INVALID(2039),

	BE_BLOCKED(2040),

	RENREN_NEED_REBIND(2041),

	SAME_CONTENT_IN_LIMIT_TIME(2042),

	CANNOT_REVIEW_ADMIN_ACCOUNT(2043),

	CANNOT_BLOCK_ADMIN_ACCOUNT(2044),

	CANNOT_REVIEW_ADMIN_POST(2045),

	HASE_ALREADY_A_FAVORER(2046),

	SINA_NEED_REBIND(2047),

	CANNOT_BIND_ANOTHER_SINA_ACCOUNT(2048),

	CAN_ONLY_COMMENT_LOVEFATEROUND_ONCE(2049),

	LOVEFATE_HAS_FINISHED(2050),

	THIS_ROUND_ALREADY_EXITED(2051),

	ALREADY_APPLY_LOVEFATE(2052),

	LOVEFATE_CREATOR_NOT_SATISFY_DEMAND(2053),

	LOVEFATE_PARTICIPATOR_ALREADY_UNSUPPORT(2054),

	LOVEFATE_ROUND_NOT_SUCCESS(2055),

	LOVEFATE_APPLICANT_ALREADY_VERIFIED(2056),

	ACCOUNT_NOT_EXIST(2057),

	AUTHCODE_INCORRECT(2058),

	CAN_NOT_BE_SELF_FAVORER(2059),
	
	SESSION_QQACCOUNT_INVALID(2060),
	
	QQ_NEED_REBIND(2061),
	
	CANNOT_BIND_ANOTHER_QQ_ACCOUNT(2062),
	
	CONTAIN_SENSITIVE_WORD(2063),
	
	CREDIT_SCORE_NOT_ENOUGH(2064),
	
	NOT_VALIDATE_INVITE_CODE(2065),
	
	NOT_VALIDATE_SCORE_TYPE(2066),
	
	ALREADY_AQUIRE_SCORE_TYPE(2067),
	
	HAS_BEEN_INVITED_ACTIVE(2068),
	
	NOT_BIND_THIRD_PART(2069),
	
	QQ_CONNECTION_ERROR(2070),
	
	ONLINE_TIME_NOT_ENOUGH(2071),
	
	PRODUCTS_TIME_NOT_FOUND(2072),
	
	ORDER_NOT_FOUND(2073),
	
	ORDER_HAS_PAID(2074),
	
	ORDER_HAS_NOT_PAID(2075),
	
	LOVEFATE_AUTH_NOT_MODIFIED(2076),
	
	LOVEFATE_STAGE_APPLICANT_NOT_MODIFIED(2077),
	
	DO_NOT_AN_APPLICANT(2100),
	
	ROOMEVENT_APPLY_HAS_FINISHED(2101),
	
	APPLICANT_HAS_GUEST(2102),
	
	APPLICANT_NOT_AUTHENTICATE(2103),
	
	ROOM_EVENT_GAME_FATE_NOT_START(2104),
	
	IN_LOVE_GUEST_CAN_NOT_ATTEND_ROUND(2105),
	
	APPLY_ROOM_EVENT_LIMIT(2106),
	
	APPLY_ROOM_EVENT_PEOPLE_LIMIT(2107),
	
	MALE_CANNOT_REATTEND_WHEN_FAILED(2108),
	
	NOT_WARM_UP_PHASE(2109),
	
	CLIENT_VERSION_LOWEST_LIMIT(2110),
	
	ROOM_EVENT_ROUND_MODERATOR_ASSIGINED(2111),
	
	USER_KICKED_BY_ROOM_ADMIN(2112),
	
	ROOM_HAS_MODERATOR(2113),
	
	ROOM_MODERATRO_LIMIT(2114),
	
	ROOM_HAS_NOT_MODERATOR(2115),
	
	USER_HAS_NOT_ROOM_OWNER(2116),
	
	NOT_BEGINER_NOT_APPLY(2117),
	
	NOT_UNWIND_ROOM_OWNER(2118),

	USER_HAS_GO_AWAY_FROM_ROOM(2119),
	
	ROOM_RECOMMEND_NOT_FOUND(2120),
	
	ROOM_MODERATOR_DENY(2121);

	private final Integer code;

	private ErrorType(final Integer code) {
		this.code = code;
	}

	public Integer getCode() {
		return code;
	}
}
